### ISSUE TITLE
Some of the parameters are exposed redundantly

### ISSUE THREAD

**Issue by amadeusp** [Sinuslabs/Bandbreite#2]
# Steps
1. Access exposed parameters via host DAW (in my case Bitwig Studio 5.2 Beta 10 Flatpak on Manjaro Linux)

# Expected behavior
Each parameter would be exposed only once.

# Bug
The parameter "Dust" is exposed 3 times whereas "Noise" is exposef 2 times, see screenshots.

# My system
```

**Comment by oskarsh** [comment]
this bug report is redundant as well ha!

**Comment by amadeusp** [comment]
@oskarsh Hahaha, don't know how this happened. 🫣
